version: '3'
services:
  discord:
    container_name: "urs-bot"
    build: .
    tty: true
    secrets:
      - gcp-token
      - bot-token

secrets:
  gcp-token:
    file: ursdiscordbot.json
  bot-token:
    file: bot-token.txt


