version: '3'
services:
  discord:
    container_name: "ursa-bot"
    build: .
    secrets:
      - gcp-token
      - bot-token
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp-token
      BOT_TOKEN: /run/secrets/bot-token
    ports:
      - 8080:8080

secrets:
  gcp-token:
    file: ursdiscordbot.json
  bot-token:
    file: bot-token.txt


